CREATE TABLE USERS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT ,
	NAME VARCHAR(50) NOT NULL ,
	EMAIL VARCHAR(255) NOT NULL ,
	PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE ROLES(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE USERS_ROLES(
	ID INT PRIMARY KEY,
	USER_ID INT,
	ROL_ID INT,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (ROL_ID) REFERENCES ROLES(ID)
);

CREATE TABLE BOOKS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(50) NOT NULL,
	AUTHOR VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	SOTCK INT(1) NOT NULL
);

CREATE TABLE USERS_BOOKS(
	ID INT PRIMARY KEY,
	USER_ID INT,
	BOOK_ID INT,
	FECHA_PRESTAMO DATE NOT NULL,
	FECHA_ENTREGA DATE,
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);